### 使用pickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
f = open('x.pkl', 'wb')

In [15]:
pickle.dump(x, f)

In [17]:
!ls

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [18]:
f = open('x.pkl', 'rb')

In [21]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# save方法
np.save('one_array', x)

In [26]:
# windows下采用该命令
!dir

 驱动器 C 中的卷没有标签。
 卷的序列号是 3EE8-D32E

 C:\Users\jiangyanfei 的目录

2018/11/20  17:19    <DIR>          .
2018/11/20  17:19    <DIR>          ..
2018/09/05  09:02    <DIR>          .android
2018/07/19  15:18    <DIR>          .astropy
2018/11/15  18:56             5,005 .bash_history
2018/09/27  10:36    <DIR>          .config
2018/08/01  11:07                53 .gitconfig
2018/07/24  13:42    <DIR>          .idlerc
2018/08/16  17:38    <DIR>          .IntelliJIdea2018.2
2018/11/20  17:13    <DIR>          .ipynb_checkpoints
2018/11/20  14:18    <DIR>          .ipython
2018/11/20  17:17    <DIR>          .jupyter
2018/07/18  09:47    <DIR>          .m2
2018/07/23  14:13    <DIR>          .matplotlib
2018/07/31  10:26    <DIR>          .mume
2018/09/27  10:35                84 .node_repl_history
2018/07/18  09:42    <DIR>          .oracle_jre_usage
2018/07/26  10:26    <DIR>          .PyCharm2018.2
2018/09/15  17:48    <DIR>          .pylint.d
2018/07/25  08:54    <DIR>          .quokka
2018/

In [28]:
# 读取
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
y = np.arange(20)

In [33]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
# savez 压缩文件
np.savez('two_array.npz', a=x,b=y)

In [36]:
!dir

 驱动器 C 中的卷没有标签。
 卷的序列号是 3EE8-D32E

 C:\Users\jiangyanfei 的目录

2018/11/20  17:23    <DIR>          .
2018/11/20  17:23    <DIR>          ..
2018/09/05  09:02    <DIR>          .android
2018/07/19  15:18    <DIR>          .astropy
2018/11/15  18:56             5,005 .bash_history
2018/09/27  10:36    <DIR>          .config
2018/08/01  11:07                53 .gitconfig
2018/07/24  13:42    <DIR>          .idlerc
2018/08/16  17:38    <DIR>          .IntelliJIdea2018.2
2018/11/20  17:13    <DIR>          .ipynb_checkpoints
2018/11/20  14:18    <DIR>          .ipython
2018/11/20  17:17    <DIR>          .jupyter
2018/07/18  09:47    <DIR>          .m2
2018/07/23  14:13    <DIR>          .matplotlib
2018/07/31  10:26    <DIR>          .mume
2018/09/27  10:35                84 .node_repl_history
2018/07/18  09:42    <DIR>          .oracle_jre_usage
2018/07/26  10:26    <DIR>          .PyCharm2018.2
2018/09/15  17:48    <DIR>          .pylint.d
2018/07/25  08:54    <DIR>          .quokka
2018/

In [37]:
c = np.load('two_array.npz')

In [39]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])