In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

### Concatenate

In [2]:
# 矩阵
arr1 = np.arange(9).reshape(3, 3)

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr2 = np.arange(9).reshape(3, 3)

In [7]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.concatenate([arr1, arr2])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.concatenate([arr1, arr2], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [14]:
# Series
s1 = Series([1, 2, 3], index=['X', 'Y', 'Z'])
s2 = Series([4, 5], index=['A', 'B'])

In [15]:
s1

X    1
Y    2
Z    3
dtype: int64

In [17]:
s2

A    4
B    5
dtype: int64

In [18]:
pd.concat([s1, s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [20]:
pd.concat([s1, s2], axis=1, sort=True)

0    1
A  NaN  4.0
B  NaN  5.0
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN

In [22]:
# DataFrame
df1= DataFrame(np.random.randn(4, 3), columns={'X','Y','Z'})
df2= DataFrame(np.random.randn(3, 3), columns={'X','Y','A'})

In [23]:
df1

Z         Y         X
0  1.036371  0.460889 -0.135493
1 -0.070975  0.385987 -0.127031
2  0.036659  0.137802  1.081739
3 -0.058709  0.185616  2.079250

In [25]:
df2

A         Y         X
0 -1.140990 -0.725807  1.458090
1  0.826909 -1.568588  1.167612
2 -0.258949  1.530428 -1.594916

In [27]:
pd.concat([df1, df2], sort=True)

A         X         Y         Z
0       NaN -0.135493  0.460889  1.036371
1       NaN -0.127031  0.385987 -0.070975
2       NaN  1.081739  0.137802  0.036659
3       NaN  2.079250  0.185616 -0.058709
0 -1.140990  1.458090 -0.725807       NaN
1  0.826909  1.167612 -1.568588       NaN
2 -0.258949 -1.594916  1.530428       NaN

### Combine

In [30]:
s1 = Series([1, np.nan, 3, np.nan], index=['A','B','C','D'])
s2 = Series([np.nan, 2, np.nan, 4], index=['A','B','C','D'])

In [31]:
s1

A    1.0
B    NaN
C    3.0
D    NaN
dtype: float64

In [32]:
s2

A    NaN
B    2.0
C    NaN
D    4.0
dtype: float64

In [33]:
s1.combine_first(s2)

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float64

In [34]:
s2.combine_first(s1)

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float64

In [41]:
df1 = DataFrame({
    'A': [1, np.nan, 3, np.nan],
    'B': [1, np.nan, 3, np.nan],
    'C': [1, np.nan, 3, np.nan]
})
df2 = DataFrame({
     'A': [np.nan, 2, np.nan, 4],
    'Y': [np.nan, 2, np.nan, 4]
})

In [42]:
df1

A    B    C
0  1.0  1.0  1.0
1  NaN  NaN  NaN
2  3.0  3.0  3.0
3  NaN  NaN  NaN

In [43]:
df2

A    Y
0  NaN  NaN
1  2.0  2.0
2  NaN  NaN
3  4.0  4.0

In [44]:
df1.combine_first(df2)

A    B    C    Y
0  1.0  1.0  1.0  NaN
1  2.0  NaN  NaN  2.0
2  3.0  3.0  3.0  NaN
3  4.0  NaN  NaN  4.0

In [45]:
df2.combine_first(df1)

A    B    C    Y
0  1.0  1.0  1.0  NaN
1  2.0  NaN  NaN  2.0
2  3.0  3.0  3.0  NaN
3  4.0  NaN  NaN  4.0