In [3]:
import numpy as np
import pandas as pd

In [5]:
# list 创建 Series
s1 = pd.Series([1, 2, 3, 4])

In [7]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
s1.values

array([1, 2, 3, 4], dtype=int64)

In [11]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
# array 创建 Series
s2 = pd.Series(np.arange(10))

In [14]:
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [15]:
# dict 创建 Series
s3 = pd.Series({'a':1, 'b':2, 'c':3})

In [17]:
s3

a    1
b    2
c    3
dtype: int64

In [19]:
s3.values

array([1, 2, 3], dtype=int64)

In [20]:
s3.index

Index(['a', 'b', 'c'], dtype='object')

In [4]:
# 指定 index 的 Series
s4 = pd.Series([1, 2, 3, 4], index={'A', 'B', 'C', 'D'})

In [5]:
s4

B    1
A    2
C    3
D    4
dtype: int64

In [7]:
# Series 转换为 dict
s4.to_dict()

{'B': 1, 'A': 2, 'C': 3, 'D': 4}

In [9]:
s5 = pd.Series(s4.to_dict())

In [11]:
s5

B    1
A    2
C    3
D    4
dtype: int64

In [13]:
# index 转换
index_1 = {'A', 'B', 'C', 'D', 'E'}
s6 = pd.Series(s5, index_1)

In [15]:
s6

C    3.0
D    4.0
B    1.0
E    NaN
A    2.0
dtype: float64

In [17]:
# 元素操作
# 判空
pd.isnull(s6)

C    False
D    False
B    False
E     True
A    False
dtype: bool

In [19]:
pd.notnull(s6)

C     True
D     True
B     True
E    False
A     True
dtype: bool

In [21]:
# 命名
s6.name = 'demo'

In [23]:
s6

C    3.0
D    4.0
B    1.0
E    NaN
A    2.0
Name: demo, dtype: float64

In [25]:
s6.index.name = 'demo index'

In [27]:
s6.index

Index(['C', 'D', 'B', 'E', 'A'], dtype='object', name='demo index')

In [29]:
s6.values

array([ 3.,  4.,  1., nan,  2.])