### 快速创建数组

In [1]:
import numpy as np

In [4]:
# randn 创建长度为10的一维数组，且数组元素满足正态分布
np.random.randn(10)

array([-0.33449844, -0.1490416 , -0.27399399,  1.0561671 , -0.40881947,
       -1.14842854, -0.57158135, -0.02221695,  0.11761491,  0.61686979])

In [6]:
# randint 返回元素限制10以内，大小为2x3的矩阵
np.random.randint(10, size=(2, 3))

array([[0, 6, 4],
       [5, 0, 8]])

In [8]:
# 生成长度为1的数组，也可以变换为多维数组 reshape() 方法
np.random.randint(10, size=(10))

array([3, 5, 2, 3, 0, 2, 5, 1, 8, 2])

In [11]:
# 变换为多维数组 reshape() 方法
np.random.randint(10, size=(10)).reshape(2, 5)

array([[8, 4, 3, 1, 0],
       [8, 6, 2, 2, 2]])

### 数组的运算

In [12]:
a = np.random.randint(10, size=(20)).reshape(4, 5)
b = np.random.randint(10, size=(20)).reshape(4, 5)

In [14]:
a

array([[4, 6, 9, 6, 4],
       [7, 0, 7, 1, 5],
       [5, 7, 5, 5, 4],
       [9, 1, 7, 3, 2]])

In [16]:
b

array([[5, 3, 6, 9, 1],
       [2, 1, 9, 2, 0],
       [8, 2, 5, 7, 9],
       [9, 4, 0, 9, 7]])

In [18]:
a + b

array([[ 9,  9, 15, 15,  5],
       [ 9,  1, 16,  3,  5],
       [13,  9, 10, 12, 13],
       [18,  5,  7, 12,  9]])

In [20]:
a - b

array([[-1,  3,  3, -3,  3],
       [ 5, -1, -2, -1,  5],
       [-3,  5,  0, -2, -5],
       [ 0, -3,  7, -6, -5]])

In [22]:
a * b

array([[20, 18, 54, 54,  4],
       [14,  0, 63,  2,  0],
       [40, 14, 25, 35, 36],
       [81,  4,  0, 27, 14]])

In [24]:
# 除法：由于数组b存在元素为0，因此，结果上做了INF的处理，并报出警告
a / b 

C:\Users\jiangyanfei\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[0.8       , 2.        , 1.5       , 0.66666667, 4.        ],
       [3.5       , 0.        , 0.77777778, 0.5       ,        inf],
       [0.625     , 3.5       , 1.        , 0.71428571, 0.44444444],
       [1.        , 0.25      ,        inf, 0.33333333, 0.28571429]])

### 快速创建矩阵

In [26]:
# mat() 进行创建
np.mat([[1, 2, 3], [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [28]:
# 数组向矩阵转换
np.mat(a)

matrix([[4, 6, 9, 6, 4],
        [7, 0, 7, 1, 5],
        [5, 7, 5, 5, 4],
        [9, 1, 7, 3, 2]])

### 矩阵的运算

In [29]:
A = np.mat(a)
B = np.mat(b)

In [31]:
A

matrix([[4, 6, 9, 6, 4],
        [7, 0, 7, 1, 5],
        [5, 7, 5, 5, 4],
        [9, 1, 7, 3, 2]])

In [33]:
B

matrix([[5, 3, 6, 9, 1],
        [2, 1, 9, 2, 0],
        [8, 2, 5, 7, 9],
        [9, 4, 0, 9, 7]])

In [35]:
A + B

matrix([[ 9,  9, 15, 15,  5],
        [ 9,  1, 16,  3,  5],
        [13,  9, 10, 12, 13],
        [18,  5,  7, 12,  9]])

In [37]:
A - B

matrix([[-1,  3,  3, -3,  3],
        [ 5, -1, -2, -1,  5],
        [-3,  5,  0, -2, -5],
        [ 0, -3,  7, -6, -5]])

In [39]:
# 矩阵乘法(满足：m*p -- p*n 相乘为 m*n矩阵)
AA = np.mat(np.random.randint(10, size=(20)).reshape(4, 5))
BB = np.mat(np.random.randint(10, size=(20)).reshape(5, 4))

In [41]:
AA

matrix([[1, 4, 3, 6, 5],
        [7, 6, 4, 9, 0],
        [4, 4, 2, 1, 8],
        [0, 1, 6, 6, 2]])

In [43]:
BB

matrix([[6, 8, 2, 2],
        [0, 7, 4, 8],
        [7, 1, 6, 5],
        [9, 9, 6, 3],
        [2, 4, 8, 9]])

In [45]:
AA * BB

matrix([[ 91, 113, 112, 112],
        [151, 183, 116, 109],
        [ 63, 103, 106, 125],
        [100,  75,  92,  74]])

### 数组常用函数

In [47]:
a = np.random.randint(10, size=(20)).reshape(4, 5)

In [48]:
a

array([[2, 2, 1, 2, 4],
       [9, 0, 7, 9, 8],
       [6, 7, 6, 8, 6],
       [2, 8, 1, 4, 8]])

In [51]:
# 返回数组元素唯一值
np.unique(a)

array([0, 1, 2, 4, 6, 7, 8, 9])

In [53]:
# 求和 以列为单位
sum(a)

array([19, 17, 15, 23, 26])

In [55]:
# 求具体行的和
sum(a[0])

11

In [58]:
# 求具体列的和
sum(a[:,0])

19

In [60]:
# 最大值
a.max()

9

In [62]:
# 具体行、列最大
max(a[0])

4

In [68]:
max(a[:,0])

9

In [64]:
max(a[:,2])

7